(()=>{
const API='https://ghar-parivar-backend.onrender.com';
const $=id=>document.getElementById(id);
const api=async(path,opt={})=>{const r=await fetch(API+path,{credentials:'include',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||d.message||'Request failed');return d};
const img= f=>f?new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)}):Promise.resolve(null);
async function publicEvents(){const box=document.querySelector('.event-grid');if(!box)return;try{const ev=await api('/events');if(!ev.length)return;box.innerHTML=ev.map(e=>`<article class="event-card">${e.photo?`<img src="${e.photo}" style="width:100%;height:220px;object-fit:cover;border-radius:14px 14px 0 0">`:`<div class="event-art gathering">📅</div>`}<div><h2>${e.title}</h2>${e.date?`<p><b>📅 ${e.date}</b></p>`:''}${e.location?`<p>📍 ${e.location}</p>`:''}<p>${e.description||''}</p></div></article>`).join('')}catch(e){console.warn(e)}}
function addStyles(){if($('event-admin-style'))return;const s=document.createElement('style');s.id='event-admin-style';s.textContent='.event-admin-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:18px 0}.event-admin-form label{display:flex;flex-direction:column;gap:6px;font-weight:700}.event-admin-form input,.event-admin-form textarea{padding:11px;border:1px solid #ccd6df;border-radius:9px;font:inherit}.event-admin-form textarea{min-height:80px}.event-admin-full{grid-column:1/-1}.event-admin-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.event-admin-card{border:1px solid #d9e2ec;border-radius:12px;padding:14px}.event-admin-card img{width:100%;height:150px;object-fit:cover;border-radius:10px}.event-admin-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}@media(max-width:700px){.event-admin-form{grid-template-columns:1fr}}';document.head.appendChild(s)}
let ready=false;
async function install(){const panel=$('admin-panel');if(!panel||ready)return;ready=true;addStyles();const tabs=panel.querySelector('.admin-tabs');const tab=document.createElement('button');tab.className='admin-tab';tab.dataset.adminTab='events';tab.textContent='📅 कार्यक्रम';tabs.appendChild(tab);const sec=document.createElement('div');sec.id='admin-events';sec.className='admin-section';panel.appendChild(sec);tab.addEventListener('click',load);}
async function load(){const box=$('admin-events');box.classList.add('active');document.querySelectorAll('#admin-panel .admin-section').forEach(x=>{if(x!==box)x.classList.remove('active')});document.querySelectorAll('#admin-panel .admin-tab').forEach(x=>x.classList.toggle('active',x.dataset.adminTab==='events'));try{const ev=await api('/admin/events');box.innerHTML=`<h2>📅 कार्यक्रम प्रबंधन</h2><p>नया कार्यक्रम जोड़ें, उसकी फोटो upload करें, या पुराने कार्यक्रम को edit/delete करें.</p><div id="event-editor"></div><button class="btn primary" id="add-event">＋ नया कार्यक्रम</button><div class="event-admin-list" style="margin-top:18px">${ev.map(e=>card(e)).join('')}</div>`;$('add-event').onclick=()=>editor({});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor(ev.find(x=>String(x.id)===b.dataset.edit)));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('यह कार्यक्रम हटाएँ?')){await api('/admin/events/'+b.dataset.delete,{method:'DELETE'});await load();publicEvents()}})}catch(e){box.innerHTML=`<p>${e.message}</p>`}}
function card(e){return `<article class="event-admin-card">${e.photo?`<img src="${e.photo}">`:'<div style="font-size:42px">📅</div>'}<h3>${e.title}</h3><p>${e.date||''}${e.location?' • '+e.location:''}</p><p>${e.description||''}</p><div class="event-admin-actions"><button class="btn ghost" data-edit="${e.id}">✏️ Edit</button><button class="btn ghost" data-delete="${e.id}">🗑️ Delete</button></div></article>`}
function editor(e){const box=$('event-editor');box.innerHTML=`<form class="event-admin-form"><label>कार्यक्रम का नाम<input id="ea-title" required value="${e.title||''}"></label><label>तारीख<input id="ea-date" type="date" value="${e.date||''}"></label><label>स्थान<input id="ea-location" value="${e.location||''}"></label><label class="event-admin-full">विवरण<textarea id="ea-desc">${e.description||''}</textarea></label><label class="event-admin-full">📷 कार्यक्रम की फोटो<input id="ea-photo" type="file" accept="image/*"></label>${e.photo?`<img src="${e.photo}" class="event-admin-full" style="max-width:320px;max-height:180px;object-fit:cover;border-radius:10px">`:''}<div class="event-admin-actions event-admin-full"><button class="btn primary">${e.id?'Save changes':'Add कार्यक्रम'}</button><button type="button" class="btn ghost" id="ea-cancel">Cancel</button></div><div id="ea-msg" class="event-admin-full"></div></form>`;$('ea-cancel').onclick=()=>box.innerHTML='';box.querySelector('form').onsubmit=async evnt=>{evnt.preventDefault();const msg=$('ea-msg');try{const file=$('ea-photo').files[0];const photo=file?await img(file):(e.photo||null);const data={title:$('ea-title').value,description:$('ea-desc').value||null,date:$('ea-date').value||null,location:$('ea-location').value||null,photo,active:true};await api(e.id?'/admin/events/'+e.id:'/admin/events',{method:e.id?'PATCH':'POST',body:JSON.stringify(data)});msg.textContent='कार्यक्रम और फोटो सुरक्षित हो गए ✓';await load();publicEvents()}catch(err){msg.textContent=err.message}}}
const observer=new MutationObserver(install);observer.observe(document.body,{childList:true,subtree:true});setInterval(install,500);setTimeout(publicEvents,1000);})();