/* GHAR PARIVAR — family data + member/admin portal */
const API_BASE="https://ghar-parivar-backend.onrender.com";
const $=id=>document.getElementById(id);
const state={slide:0,user:null,privateData:null,adminMembers:[]};
const families=[{id:"dawar",name:"डावर परिवार",description:"डावर परिवार की पीढ़ियां और रिश्ते।",icon:"👨‍👩‍👧‍👦",members:[
{name:"शंकरलाल डावर",designation:"दादा",role:"grandparent",icon:"👴"},{name:"कंचन बाई",designation:"दादी",role:"grandparent",icon:"👵"},{name:"मुकेश डावर",designation:"पिता",occupation:"Ex-service man (Army)",role:"parent",icon:"👨"},{name:"माया",designation:"माता",occupation:"Inspector (Agriculture Department)",role:"parent",icon:"👩"},{name:"तनमय डावर",designation:"पुत्र • विद्यार्थी",occupation:"Student",role:"child",icon:"👦"},{name:"हर्षिता डावर",designation:"पुत्री • विद्यार्थी",occupation:"Student",role:"child",icon:"👧"}
]}];
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));const page=$(id);if(!page)return;page.classList.add("active");if(location.hash!=="#"+id)history.pushState({page:id},"","#"+id);window.scrollTo({top:0,behavior:"smooth"});if(id==="dashboard")loadPrivate()}
window.showPage=showPage;
function navigate(e){const el=e.target.closest("[data-page]");if(!el)return;e.preventDefault();showPage(el.dataset.page);$("mobile-nav")?.classList.remove("open")}
document.addEventListener("click",navigate);
window.addEventListener("popstate",()=>showPage((location.hash||"#home").slice(1)));
$("menu-btn")?.addEventListener("click",()=>$("mobile-nav")?.classList.toggle("open"));
const slides=[...document.querySelectorAll(".hero-slide")],dots=[...document.querySelectorAll(".dot")];
function setSlide(n){if(!slides.length)return;state.slide=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle("active",i===state.slide));dots.forEach((d,i)=>d.classList.toggle("active",i===state.slide))}
document.querySelector(".slide-arrow.prev")?.addEventListener("click",e=>{e.stopPropagation();setSlide(state.slide-1)});
document.querySelector(".slide-arrow.next")?.addEventListener("click",e=>{e.stopPropagation();setSlide(state.slide+1)});
dots.forEach((d,i)=>d.addEventListener("click",e=>{e.stopPropagation();setSlide(i)}));
setInterval(()=>setSlide(state.slide+1),7000);
async function api(path,options={}){const res=await fetch(API_BASE+path,{credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.detail||data.message||`Request failed (${res.status})`);return data}
async function loadHomeMedia(){try{const media=await api("/media");media.forEach(m=>{const target=m.slot==="slide1"?document.querySelector(".art-one"):m.slot==="slide2"?document.querySelector(".art-two"):m.slot==="slide3"?document.querySelector(".art-three"):null;if(target){target.style.backgroundImage=`url("${m.image_data}")`;target.style.backgroundSize="cover";target.style.backgroundPosition="center"}})}catch(e){}}
function renderFamilies(){const box=$("family-grid");if(!box)return;box.innerHTML=families.map(f=>`<article class="family-card"><div class="family-visual">${f.icon}</div><div class="family-content"><div class="section-label">FAMILY • परिवार</div><h2>${f.name}</h2><p>${f.description}</p><button onclick="openFamily('${f.id}')">परिवार वृक्ष देखें →</button></div></article>`).join("")}
function node(m){return `<div class="tree-node ${m.role}"><div class="tree-avatar">${m.icon}</div><div class="tree-name">${m.name}</div><div class="tree-designation">${m.designation}</div>${m.occupation?`<div class="tree-occupation">${m.occupation}</div>`:""}</div>`}
window.openFamily=id=>{const f=families.find(x=>x.id===id);if(!f)return;const g=f.members.filter(m=>m.role==="grandparent"),p=f.members.filter(m=>m.role==="parent"),c=f.members.filter(m=>m.role==="child");$("family-detail").innerHTML=`<div class="detail-panel"><div class="section-label">FAMILY TREE • परिवार वृक्ष</div><h2>${f.icon} ${f.name}</h2><p>${f.description}</p><div class="family-tree"><div class="tree-level">${g.map(node).join("")}</div><div class="tree-connector"></div><div class="tree-level">${p.map(node).join("")}</div><div class="tree-connector"></div><div class="tree-level">${c.map(node).join("")}</div></div><div class="tree-private-note">🔒 निजी फोन, ईमेल, पता और अन्य जानकारी केवल अधिकृत लॉगिन के बाद उपलब्ध होगी।</div><button class="btn primary" data-page="login">🔐 निजी जानकारी के लिए लॉगिन</button></div>`;$("family-detail").scrollIntoView({behavior:"smooth"})};
renderFamilies();
$("search-input")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase().trim(),box=$("search-results");if(!q){box.innerHTML="";return}const r=families.flatMap(f=>f.members.map(m=>({...m,family:f.name}))).filter(m=>(m.name+m.designation+m.family).toLowerCase().includes(q));box.innerHTML=r.length?r.map(m=>`<div class="search-result"><b>${m.icon} ${m.name}</b><span>${m.designation} • ${m.family}</span></div>`).join(""):"<p>कोई सदस्य नहीं मिला।</p>"});
async function checkSession(){try{state.user=await api("/me")}catch{state.user=null}}checkSession();
$("login-form")?.addEventListener("submit",async e=>{e.preventDefault();const msg=$("login-message");msg.textContent="लॉगिन हो रहा है…";try{await api("/login",{method:"POST",body:JSON.stringify({username:$("username").value.trim(),password:$("password").value})});state.user=await api("/me");e.target.reset();msg.textContent="";showPage("dashboard")}catch(err){msg.textContent=err.message}});
function renderPrivateProfile(m){const box=$("private-detail");if(!box)return;const fields=[['📱 मोबाइल',m.phone],['✉️ ईमेल',m.email],['🎂 जन्मदिन',m.birthday],['🏠 पता',m.address],['🎓 शिक्षा',m.education],['💼 पेशा',m.profession],['📝 परिचय',m.biography],['🏆 उपलब्धियां',m.achievements],['💭 यादें',m.memories]];box.innerHTML=`<article class="detail-panel private-profile-card"><button class="btn ghost" type="button" onclick="document.getElementById('private-detail').innerHTML=''">← प्रोफाइल बंद करें</button><div class="profile-heading"><div class="tree-avatar">${m.avatar&&m.avatar.startsWith('data:image')?`<img src="${m.avatar}" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`:m.avatar||'👤'}</div><div><div class="section-label">PRIVATE PROFILE • निजी प्रोफाइल</div><h2>${m.name}</h2><p>${m.designation||'परिवार सदस्य'}${m.relation?' • '+m.relation:''}</p></div></div><div class="profile-fields">${fields.filter(x=>x[1]).map(x=>`<div class="profile-field"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("")||'<p>इस सदस्य के लिए अभी निजी विवरण उपलब्ध नहीं है।</p>'}</div></article>`;box.scrollIntoView({behavior:"smooth",block:"start"})}
window.renderPrivateProfile=renderPrivateProfile;
async function loadPrivate(){const box=$("private-grid");if(!box)return;if(!state.user){box.innerHTML="<p>कृपया पहले लॉगिन करें।</p>";return}$("welcome-user").textContent=state.user.role==="admin"?`स्वागत है, ${state.user.username} • Administrator`: `स्वागत है, ${state.user.username}`;if(state.user.role==="admin"){renderAdminDashboard();return}try{state.privateData=await api("/family/private");const members=state.privateData.members||[];box.innerHTML=members.map((m,i)=>`<article class="private-card private-card-clickable" role="button" tabindex="0" onclick="renderPrivateProfile(state.privateData.members[${i}])" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();renderPrivateProfile(state.privateData.members[${i}])}"><div class="private-avatar">${m.avatar&&m.avatar.startsWith('data:image')?`<img src="${m.avatar}" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`:m.avatar||'👤'}</div><h3>${m.name}</h3><p class="private-designation">${m.designation||"परिवार सदस्य"}</p><span>प्रोफाइल देखें →</span></article>`).join("")||"<p>अभी निजी सदस्य जानकारी उपलब्ध नहीं है।</p>"}catch(err){box.innerHTML=`<p>${err.message}</p>`}}
function adminStyles(){if($("admin-inline-style"))return;const s=document.createElement("style");s.id="admin-inline-style";s.textContent=`.admin-panel{margin-top:24px;background:#fff;border:1px solid #d9e2ec;border-radius:18px;padding:24px;box-shadow:0 10px 30px rgba(16,42,67,.08)}.admin-tabs{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.admin-tab{border:1px solid #ccd6df;background:#f6f8fa;border-radius:10px;padding:10px 16px;cursor:pointer;font-weight:700}.admin-tab.active{background:#102a43;color:#fff}.admin-section{display:none}.admin-section.active{display:block}.admin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.admin-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.admin-form label{display:flex;flex-direction:column;gap:6px;font-weight:700}.admin-form input,.admin-form textarea,.admin-form select{padding:11px;border:1px solid #ccd6df;border-radius:9px;font:inherit}.admin-form textarea{min-height:80px;resize:vertical}.admin-full{grid-column:1/-1}.admin-member{border:1px solid #d9e2ec;border-radius:12px;padding:14px;background:#fbfcfd}.admin-member img{width:54px;height:54px;border-radius:50%;object-fit:cover}.admin-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.admin-photo{border:1px dashed #c6d1db;border-radius:12px;padding:16px}.admin-photo img{width:100%;max-height:160px;object-fit:cover;border-radius:10px;margin:8px 0}.admin-msg{margin:10px 0;font-weight:700}.admin-danger{background:#8b1e1e!important;color:#fff!important}@media(max-width:700px){.admin-form{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function adminShell(){const dash=$("dashboard");if(!dash)return;adminStyles();let panel=$("admin-panel");if(panel)return panel=document.createElement("div");panel=document.createElement("div");panel.id="admin-panel";panel.className="admin-panel";panel.innerHTML=`<div class="admin-tabs"><button class="admin-tab active" data-admin-tab="members">👥 सदस्य</button><button class="admin-tab" data-admin-tab="users">🔐 खाते</button><button class="admin-tab" data-admin-tab="photos">🖼️ फोटो</button></div><div id="admin-members" class="admin-section active"></div><div id="admin-users" class="admin-section"></div><div id="admin-photos" class="admin-section"></div>`;dash.querySelector("#private-grid")?.after(panel);panel.addEventListener("click",e=>{const tab=e.target.closest("[data-admin-tab]");if(tab){panel.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));tab.classList.add("active");panel.querySelectorAll(".admin-section").forEach(x=>x.classList.remove("active"));$("admin-"+tab.dataset.adminTab).classList.add("active");if(tab.dataset.adminTab==="users")loadAdminUsers();if(tab.dataset.adminTab==="photos")loadAdminPhotos()}});return panel}
function memberForm(m={}){return `<form id="member-form" class="admin-form"><input type="hidden" id="mf-id" value="${m.id||''}"><label>Family ID<input id="mf-family" required value="${m.family_id||'dawar'}"></label><label>Name<input id="mf-name" required value="${m.name||''}"></label><label>Designation<input id="mf-designation" value="${m.designation||''}"></label><label>Relation<input id="mf-relation" value="${m.relation||''}"></label><label>Generation<select id="mf-generation"><option ${m.generation==='grandparent'?'selected':''}>grandparent</option><option ${m.generation==='parent'?'selected':''}>parent</option><option ${m.generation==='child'?'selected':''}>child</option></select></label><label>Parent ID<input id="mf-parent" type="number" value="${m.parent_id||''}"></label><label>Spouse ID<input id="mf-spouse" type="number" value="${m.spouse_id||''}"></label><label>Phone<input id="mf-phone" value="${m.phone||''}"></label><label>Email<input id="mf-email" value="${m.email||''}"></label><label>Birthday<input id="mf-birthday" value="${m.birthday||''}"></label><label>Address<input id="mf-address" value="${m.address||''}"></label><label>Education<input id="mf-education" value="${m.education||''}"></label><label>Profession<input id="mf-profession" value="${m.profession||''}"></label><label class="admin-full">Biography<textarea id="mf-bio">${m.biography||''}</textarea></label><label>Achievements<textarea id="mf-achievements">${m.achievements||''}</textarea></label><label>Memories<textarea id="mf-memories">${m.memories||''}</textarea></label><label>Profile photo<input id="mf-photo" type="file" accept="image/*"></label><div class="admin-actions admin-full"><button class="btn primary">${m.id?'Save changes':'Add member'}</button><button type="button" class="btn ghost" onclick="document.getElementById('member-editor').innerHTML=''">Cancel</button></div><div id="member-msg" class="admin-msg admin-full"></div></form>`}
function memberPayload(){return {family_id:$("mf-family").value,name:$("mf-name").value,designation:$("mf-designation").value||null,relation:$("mf-relation").value||null,generation:$("mf-generation").value,parent_id:$("mf-parent").value?Number($("mf-parent").value):null,spouse_id:$("mf-spouse").value?Number($("mf-spouse").value):null,phone:$("mf-phone").value||null,email:$("mf-email").value||null,birthday:$("mf-birthday").value||null,address:$("mf-address").value||null,education:$("mf-education").value||null,profession:$("mf-profession").value||null,biography:$("mf-bio").value||null,achievements:$("mf-achievements").value||null,memories:$("mf-memories").value||null,avatar:window._memberPhoto||null}}
async function readImage(file){if(!file)return null;return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
window.editAdminMember=m=>{window._memberPhoto=m.avatar||null;$("member-editor").innerHTML=memberForm(m);$("member-form").addEventListener("submit",async e=>{e.preventDefault();const msg=$("member-msg");try{const f=$("mf-photo").files[0];if(f)window._memberPhoto=await readImage(f);const id=$("mf-id").value;await api(id?`/admin/members/${id}`:"/admin/members",{method:id?"PATCH":"POST",body:JSON.stringify(memberPayload())});msg.textContent="सहेज दिया गया ✓";await loadAdminMembers()}catch(err){msg.textContent=err.message}})};
window.deleteAdminMember=async id=>{if(!confirm("इस सदस्य को हटाना है?"))return;try{await api(`/admin/members/${id}`,{method:"DELETE"});await loadAdminMembers()}catch(e){alert(e.message)}};
async function loadAdminMembers(){const box=$("admin-members");if(!box)return;try{state.adminMembers=await api("/admin/members");box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><h2>परिवार सदस्य प्रबंधन</h2><p>नाम, designation, रिश्ते, निजी जानकारी और profile photo यहाँ से बदलें।</p></div><button class="btn primary" onclick="document.getElementById('member-editor').innerHTML=memberForm();editAdminMember({})">＋ नया सदस्य</button></div><div id="member-editor"></div><div class="admin-grid">${state.adminMembers.map(m=>`<article class="admin-member"><div style="display:flex;gap:12px;align-items:center">${m.avatar&&m.avatar.startsWith('data:image')?`<img src="${m.avatar}">`:'<div style="font-size:36px">👤</div>'}<div><b>${m.name}</b><div>${m.designation||'परिवार सदस्य'}</div><small>${m.family_id}</small></div></div><div class="admin-actions"><button class="btn ghost" onclick='editAdminMember(${JSON.stringify(m).replace(/'/g,"&#39;")})'>✏️ संपादित करें</button><button class="btn ghost admin-danger" onclick="deleteAdminMember(${m.id})">हटाएँ</button></div></article>`).join("")}</div>`}catch(e){box.innerHTML=`<p>${e.message}</p>`}}
async function loadAdminUsers(){const box=$("admin-users");if(!box)return;try{const users=await api("/admin/users");box.innerHTML=`<h2>परिवार लॉगिन खाते</h2><p>अधिकृत परिवार खातों को बनाएँ और disable करें।</p><form id="new-user-form" class="admin-form"><label>Username<input id="new-username" required></label><label>Password<input id="new-password" type="password" minlength="8" required></label><label>Family ID<input id="new-family" value="dawar" required></label><div><button class="btn primary">खाता बनाएँ</button></div><div id="new-user-msg" class="admin-msg"></div></form><div class="admin-grid" style="margin-top:18px">${users.map(u=>`<article class="admin-member"><b>${u.username}</b><div>Role: ${u.role}</div><div>Family: ${u.family_id||'—'}</div><div>Status: ${u.active?'Active':'Disabled'}</div>${u.role!=='admin'&&u.active?`<button class="btn ghost admin-danger" style="margin-top:8px" onclick="disableAdminUser(${u.id})">Disable</button>`:''}</article>`).join("")}</div>`;$("new-user-form").addEventListener("submit",async e=>{e.preventDefault();try{await api("/admin/users",{method:"POST",body:JSON.stringify({username:$("new-username").value,password:$("new-password").value,family_id:$("new-family").value})});$("new-user-msg").textContent="खाता बनाया गया ✓";e.target.reset();await loadAdminUsers()}catch(err){$("new-user-msg").textContent=err.message}})}catch(e){box.innerHTML=`<p>${e.message}</p>`}}
window.disableAdminUser=async id=>{try{await api(`/admin/users/${id}/disable`,{method:"POST"});await loadAdminUsers()}catch(e){alert(e.message)}};
async function loadAdminPhotos(){const box=$("admin-photos");if(!box)return;try{const media=await api("/admin/media");box.innerHTML=`<h2>होम स्लाइडशो फोटो</h2><p>Slide 1, Slide 2 और Slide 3 के फोटो यहाँ upload करें। आपकी नई collage को <b>slide2</b> में डालें।</p><form id="photo-form" class="admin-form"><label>Slide<select id="photo-slot"><option value="slide1">Slide 1</option><option value="slide2" selected>Slide 2</option><option value="slide3">Slide 3</option></select></label><label>Photo<input id="photo-file" type="file" accept="image/*" required></label><label class="admin-full">Caption<input id="photo-caption"></label><div><button class="btn primary">📤 Upload photo</button></div><div id="photo-msg" class="admin-msg"></div></form><div class="admin-grid" style="margin-top:18px">${media.map(m=>`<article class="admin-photo"><b>${m.slot}</b>${m.image_data.startsWith('data:image')?`<img src="${m.image_data}">`:''}<div>${m.caption||''}</div><button class="btn ghost admin-danger" onclick="deleteAdminPhoto(${m.id})">Delete</button></article>`).join("")}</div>`;$("photo-form").addEventListener("submit",async e=>{e.preventDefault();const msg=$("photo-msg");try{const data=await readImage($("photo-file").files[0]);await api("/admin/media",{method:"POST",body:JSON.stringify({slot:$("photo-slot").value,image_data:data,caption:$("photo-caption").value||null,active:true})});msg.textContent="फोटो upload हो गया ✓";e.target.reset();await loadAdminPhotos();await loadHomeMedia()}catch(err){msg.textContent=err.message}})}catch(e){box.innerHTML=`<p>${e.message}</p>`}}
window.deleteAdminPhoto=async id=>{if(!confirm("यह फोटो हटाएँ?"))return;try{await api(`/admin/media/${id}`,{method:"DELETE"});await loadAdminPhotos();await loadHomeMedia()}catch(e){alert(e.message)}};
async function renderAdminDashboard(){const panel=adminShell();await loadAdminMembers();panel?.querySelector("[data-admin-tab='members']")?.classList.add("active")}
$("logout")?.addEventListener("click",async()=>{try{await api("/logout",{method:"POST"})}catch{}state.user=null;showPage("home")});
loadHomeMedia();
const initial=(location.hash||"#home").slice(1);if($(initial))showPage(initial);