/* GHAR PARIVAR launch upgrade: dynamic families + family photos + improved tree + slideshow fix */
(()=>{
const API='https://ghar-parivar-backend.onrender.com';
const $=id=>document.getElementById(id);
const api=async(path,opt={})=>{const r=await fetch(API+path,{credentials:'include',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||d.message||`Request failed (${r.status})`);return d};
const readImage=f=>f?new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)}):Promise.resolve(null);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

/* Fix: /media returns newest first. The old loop let older duplicate uploads overwrite newer ones. */
async function loadSlides(){try{const media=await api('/media');const latest={};media.forEach(m=>{if(!latest[m.slot])latest[m.slot]=m});[['slide1','.art-one'],['slide2','.art-two'],['slide3','.art-three']].forEach(([slot,sel])=>{const m=latest[slot],el=document.querySelector(sel);if(el&&m?.image_data){el.style.backgroundImage=`url("${m.image_data}")`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.dataset.mediaLoaded='1'}})}catch(e){console.warn('slideshow:',e)}}

async function loadFamilies(){const box=$('family-grid');if(!box)return;try{const fs=await api('/families');box.innerHTML=fs.map(f=>`<article class="family-card dynamic-family-card"><div class="family-visual" style="${f.photo?`background-image:url(${f.photo});background-size:cover;background-position:center;`:''}">${f.photo?'':(f.icon||'👨‍👩‍👧‍👦')}</div><div class="family-content"><div class="section-label">FAMILY • परिवार</div><h2>${esc(f.name)}</h2><p>${esc(f.description||'परिवार की पीढ़ियां और रिश्ते।')}</p><button class="btn primary" data-open-family="${esc(f.id)}">परिवार वृक्ष देखें →</button></div></article>`).join('')||'<p>अभी कोई परिवार उपलब्ध नहीं है।</p>';box.querySelectorAll('[data-open-family]').forEach(b=>b.onclick=()=>openDynamicFamily(b.dataset.openFamily))}catch(e){console.warn('families:',e)}}
function avatar(m){return m.avatar&&String(m.avatar).startsWith('data:image')?`<img src="${m.avatar}" alt="${esc(m.name)}">`:'<span class="tree-emoji">👤</span>'}
function treeNode(m){return `<article class="tree-node-v2" data-member="${m.id}"><div class="tree-avatar-v2">${avatar(m)}</div><div class="tree-name">${esc(m.name)}</div><div class="tree-designation">${esc(m.designation||'परिवार सदस्य')}</div>${m.relation?`<div class="tree-relation">${esc(m.relation)}</div>`:''}</article>`}
function couple(m,members){const spouse=m.spouse_id?members.find(x=>Number(x.id)===Number(m.spouse_id)):null;return spouse&&Number(m.id)<Number(spouse.id)?`<div class="couple-v2"><div>${treeNode(m)}</div><div class="spouse-link">♥</div><div>${treeNode(spouse)}</div></div>`:spouse?'':treeNode(m)}
async function openDynamicFamily(id){try{const d=await api('/families/'+encodeURIComponent(id));const f=d.family||{},members=d.members||[];const byGen=g=>members.filter(m=>(m.generation||'child')===g);const levels=[['grandparent','दादा-दादी / वरिष्ठ पीढ़ी'],['parent','माता-पिता'],['child','संतान / भाई-बहन']];let html=`<div class="detail-panel dynamic-tree-panel"><button class="btn ghost" data-page="families">← परिवार सूची</button><div class="section-label">FAMILY TREE • परिवार वृक्ष</div><div class="family-detail-heading">${f.photo?`<img src="${f.photo}" class="family-detail-photo">`:''}<div><h2>${esc(f.name)}</h2><p>${esc(f.description||'')}</p></div></div><div class="tree-v2">`;for(const [gen,label] of levels){const arr=byGen(gen);if(!arr.length)continue;const rendered=[];arr.forEach(m=>{if(m.spouse_id&&members.some(x=>Number(x.id)===Number(m.spouse_id))) rendered.push(couple(m,members));else rendered.push(treeNode(m))});html+=`<div class="tree-level-v2"><div class="tree-level-label">${label}</div><div class="tree-cards-v2">${rendered.join('')}</div></div>`;if(gen!=='child')html+=`<div class="parent-arrow-v2">↓<span>संतान</span></div>`}html+=`</div><p class="tree-legend-v2">↔ पति/पत्नी &nbsp; • &nbsp; ↓ माता-पिता से संतान &nbsp; • &nbsp; भाई-बहन एक ही स्तर पर</p><div class="tree-private-note">🔒 निजी मोबाइल, ईमेल, पता और अन्य विवरण केवल अधिकृत लॉगिन के बाद उपलब्ध होंगे।</div><button class="btn primary" data-page="login">🔐 निजी जानकारी के लिए लॉगिन</button></div>`;$('family-detail').innerHTML=html;$('family-detail').querySelector('[data-page]')?.addEventListener('click',()=>showPage('login'));$('family-detail').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){alert(e.message)}}

function addUpgradeStyles(){if($('site-upgrade-style'))return;const s=document.createElement('style');s.id='site-upgrade-style';s.textContent=`.dynamic-family-card .family-visual{min-height:220px;background-color:#eef2f5;background-repeat:no-repeat}.family-detail-heading{display:flex;gap:20px;align-items:center;margin:18px 0}.family-detail-photo{width:130px;height:100px;object-fit:cover;border-radius:14px}.tree-v2{margin-top:25px}.tree-level-label{text-align:center;font-weight:800;margin:12px 0}.tree-cards-v2{display:flex;justify-content:center;align-items:center;gap:18px;flex-wrap:wrap}.tree-node-v2{width:180px;min-height:155px;background:#fff;border:1px solid #d8e1e8;border-radius:16px;padding:14px;text-align:center;box-shadow:0 7px 22px rgba(16,42,67,.08);position:relative}.tree-avatar-v2{width:72px;height:72px;border-radius:50%;margin:0 auto 8px;overflow:hidden;background:#eef2f5;display:grid;place-items:center}.tree-avatar-v2 img{width:100%;height:100%;object-fit:cover}.tree-emoji{font-size:30px}.tree-name{font-weight:800}.tree-designation{font-size:13px;margin-top:4px}.tree-relation{font-size:12px;opacity:.7;margin-top:3px}.couple-v2{display:flex;align-items:center;gap:8px}.spouse-link{font-size:18px}.parent-arrow-v2{text-align:center;font-size:28px;font-weight:900;margin:12px}.parent-arrow-v2 span{display:block;font-size:11px;font-weight:700}.tree-legend-v2{text-align:center;font-size:13px;opacity:.75;margin:18px}.admin-family-form{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.admin-family-form label{display:flex;flex-direction:column;gap:6px;font-weight:700}.admin-family-form input,.admin-family-form textarea{padding:11px;border:1px solid #ccd6df;border-radius:9px;font:inherit}.admin-family-form textarea{min-height:80px}.admin-family-full{grid-column:1/-1}.family-admin-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.family-admin-card{border:1px solid #d9e2ec;border-radius:12px;padding:14px}.family-admin-card img{width:100%;height:150px;object-fit:cover;border-radius:10px}.family-admin-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}@media(max-width:700px){.admin-family-form{grid-template-columns:1fr}.family-detail-heading{flex-direction:column;align-items:flex-start}.couple-v2{flex-direction:column}}`;document.head.appendChild(s)}

let familyAdminReady=false;
async function installFamilyAdmin(){const panel=$('admin-panel');if(!panel||familyAdminReady)return;familyAdminReady=true;addUpgradeStyles();const tabs=panel.querySelector('.admin-tabs');const tab=document.createElement('button');tab.className='admin-tab';tab.dataset.adminTab='families';tab.textContent='👨‍👩‍👧‍👦 परिवार';tabs.insertBefore(tab,tabs.firstChild);const sec=document.createElement('div');sec.id='admin-families';sec.className='admin-section';panel.appendChild(sec);tab.onclick=loadFamilyAdmin}
async function loadFamilyAdmin(){const box=$('admin-families');document.querySelectorAll('#admin-panel .admin-section').forEach(x=>x.classList.remove('active'));box.classList.add('active');document.querySelectorAll('#admin-panel .admin-tab').forEach(x=>x.classList.toggle('active',x===document.querySelector('[data-admin-tab="families"]')));try{const fs=await api('/admin/families');box.innerHTML=`<h2>👨‍👩‍👧‍👦 परिवार प्रबंधन</h2><p>परिवार जोड़ें, नाम/विवरण बदलें और group photo upload करें।</p><div id="family-editor"></div><button class="btn primary" id="new-family">＋ नया परिवार</button><div class="family-admin-list" style="margin-top:18px">${fs.map(f=>`<article class="family-admin-card">${f.photo?`<img src="${f.photo}">`:'<div style="font-size:44px">👨‍👩‍👧‍👦</div>'}<h3>${esc(f.name)}</h3><p>${esc(f.description||'')}</p><small>ID: ${esc(f.id)}</small><div class="family-admin-actions"><button class="btn ghost" data-edit-family="${esc(f.id)}">✏️ Edit</button><button class="btn ghost admin-danger" data-delete-family="${esc(f.id)}">🗑️ Delete</button></div></article>`).join('')}</div>`;$('new-family').onclick=()=>familyEditor({});box.querySelectorAll('[data-edit-family]').forEach(b=>b.onclick=()=>familyEditor(fs.find(x=>x.id===b.dataset.editFamily)));box.querySelectorAll('[data-delete-family]').forEach(b=>b.onclick=async()=>{if(confirm('यह परिवार हटाएँ?')){await api('/admin/families/'+encodeURIComponent(b.dataset.deleteFamily),{method:'DELETE'});await loadFamilyAdmin();loadFamilies()}})}catch(e){box.innerHTML=`<p>${e.message}</p>`}}
function familyEditor(f={}){const box=$('family-editor');box.innerHTML=`<form class="admin-family-form"><label>Family ID<input id="ff-id" required pattern="[a-zA-Z0-9_-]+" value="${esc(f.id||'')}"></label><label>Family name<input id="ff-name" required value="${esc(f.name||'')}"></label><label class="admin-family-full">Description<textarea id="ff-desc">${esc(f.description||'')}</textarea></label><label>Group photo<input id="ff-photo" type="file" accept="image/*"></label>${f.photo?`<img src="${f.photo}" class="admin-family-full" style="max-width:320px;max-height:180px;object-fit:cover;border-radius:10px">`:''}<div class="family-admin-actions admin-family-full"><button class="btn primary">${f.id?'Save changes':'Add family'}</button><button type="button" class="btn ghost" id="ff-cancel">Cancel</button></div><div id="ff-msg" class="admin-family-full"></div></form>`;$('ff-cancel').onclick=()=>box.innerHTML='';box.querySelector('form').onsubmit=async e=>{e.preventDefault();const msg=$('ff-msg');try{const file=$('ff-photo').files[0];const photo=file?await readImage(file):(f.photo||null);const data={id:$('ff-id').value.trim(),name:$('ff-name').value.trim(),description:$('ff-desc').value||null,icon:'👨‍👩‍👧‍👦',photo,active:true};await api(f.id?'/admin/families/'+encodeURIComponent(f.id):'/admin/families',{method:f.id?'PATCH':'POST',body:JSON.stringify(data)});msg.textContent='परिवार और group photo सुरक्षित हो गए ✓';await loadFamilyAdmin();loadFamilies()}catch(err){msg.textContent=err.message}}}

addUpgradeStyles();
/* Wait until the original family container exists, then replace hard-coded cards with database data. */
loadSlides();loadFamilies();
const mo=new MutationObserver(()=>{installFamilyAdmin()});mo.observe(document.body,{childList:true,subtree:true});setInterval(installFamilyAdmin,700);
})();