/* GHAR PARIVAR — Sumra family public data */
(function(){
  const DATA={
    root:['Dhulji Ram','Nadan Bai'],
    branches:[
      {p:['Rakesh','Sakuntala'],children:[{p:['Riya']},{p:['Rahul']}]},
      {p:['Dinesh','Sushila'],children:[{p:['Abhishek','Jagarati']},{p:['Sonali']}]},
      {p:['Babulal','Santosh'],children:[{p:['Puja']},{p:['Shubham']}]},
      {p:['Mahesh','Kavita'],children:[{p:['Akshat']},{p:['Jayant']}]}
    ]
  };
  const person=n=>`<div class="s-person"><div class="s-avatar">👤</div><strong>${n}</strong></div>`;
  const couple=p=>p.length>1?`<div class="s-couple">${person(p[0])}<span class="s-dash">—</span>${person(p[1])}</div>`:person(p[0]);
  function tree(){return `<div class="s-tree"><div class="s-root">${couple(DATA.root)}</div><div class="s-line"></div><div class="s-branches">${DATA.branches.map(b=>`<section class="s-branch"><div class="s-parent">${couple(b.p)}</div><div class="s-line"></div><div class="s-children">${b.children.map(c=>`<div class="s-child">${couple(c.p)}</div>`).join('')}</div></section>`).join('')}</div></div>`}
  function open(){const d=document.getElementById('family-detail');if(!d)return;d.innerHTML=`<div class="detail-panel sumra-detail"><button class="btn ghost" type="button" id="sumra-back">← परिवार सूची</button><div class="section-label">SUMRA FAMILY • सुमरा परिवार</div><h2>सुमरा परिवार</h2><p>धुलजी राम और नादन बाई से आगे बढ़ती सुमरा परिवार की पीढ़ियाँ।</p>${tree()}<div class="tree-private-note">🔒 मोबाइल, ईमेल, पता और अन्य निजी जानकारी केवल अधिकृत लॉगिन के बाद उपलब्ध होगी।</div></div>`;document.getElementById('sumra-back').onclick=()=>{d.innerHTML='';render()};d.scrollIntoView({behavior:'smooth',block:'start'})}
  function render(){const grid=document.getElementById('family-grid');if(!grid)return;if(!document.getElementById('sumra-family-card'))grid.insertAdjacentHTML('beforeend',`<article id="sumra-family-card" class="family-card sumra-family-card"><div class="family-visual">👨‍👩‍👧‍👦</div><div class="family-content"><div class="section-label">FAMILY • परिवार</div><h2>सुमरा परिवार</h2><p>धुलजी राम और नादन बाई से आगे बढ़ती सुमरा परिवार की पीढ़ियाँ।</p><button type="button" id="sumra-open-btn">परिवार वृक्ष देखें →</button></div></article>`);const b=document.getElementById('sumra-open-btn');if(b&&!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',open)}}
  const style=document.createElement('style');style.textContent=`.sumra-family-card{display:block}.s-tree{padding:20px 0}.s-root,.s-parent{text-align:center}.s-couple{display:inline-flex;align-items:center;justify-content:center;gap:10px;padding:10px 14px;border:1px solid #d9e2ec;border-radius:14px;background:#fff;box-shadow:0 5px 15px rgba(16,42,67,.06);flex-wrap:wrap}.s-person{display:flex;align-items:center;gap:7px}.s-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#eef3f7}.s-dash{font-weight:700;color:#52606d}.s-line{height:24px;width:2px;background:#b7c5d2;margin:0 auto}.s-branches{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.s-branch{border:1px solid #d9e2ec;border-radius:18px;padding:18px;background:#fbfcfd}.s-children{position:relative;display:flex;gap:10px;justify-content:center;flex-wrap:wrap}.s-child{padding:8px;border:1px solid #e1e7ed;border-radius:12px;background:#fff;text-align:center}.s-child .s-avatar{width:30px;height:30px;font-size:16px}@media(max-width:700px){.s-branches{grid-template-columns:1fr}.s-couple{max-width:100%;font-size:14px}}`;document.head.appendChild(style);let tries=0;function boot(){render();if(++tries<20)setTimeout(boot,500)}boot();new MutationObserver(render).observe(document.body,{childList:true,subtree:true});})();